name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  Register-Image:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get-commit.outputs.hash }}
    steps:
      # 1. Checkout do código
      - name: Checkout mode
        uses: actions/checkout@v2

      # 2. Login no Amazon ECR
      - name: Log in to Amazon ECR
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}

      # 3. Obter hash curto do commit
      - name: Get short commit hash
        id: get-commit
        run: |
          calculatedSha=$(git rev-parse --short "${{ github.sha }}")
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      # 4. 
      - name: Build and push Docker image
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          REPOSITORY_URI: ${{ secrets.ECR_URI }}
        run: |
          cd Docker
          IMAGE_TAG=${COMMIT_SHORT_SHA:-dev}
          docker build -t $REPOSITORY_URI:$IMAGE_TAG .
          docker push $REPOSITORY_URI:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

  Scan-Container:
    runs-on: ubuntu-latest
    needs: Register-Image
    steps:

      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Instalação do Snyk CLI
      - name: Install and auth Snyk CLI
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npm install -g snyk
          snyk auth "$SNYK_TOKEN"

      # 3. Login no Amazon ECR
      - name: Log in Amazon
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}
          
      # 4. Obter o hash curto do commit
      - name: Get short commit hash
        id: get-commit
        run: |
          calculatedSha=$(git rev-parse --short "${{ github.sha }}")
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      # 5. Executar o Snyk Scan no container
      - name: Snyk Docker Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          REPOSITORY_URI: ${{ secrets.ECR_URI }}
        run: |
          IMAGE_TAG=${COMMIT_SHORT_SHA:-dev}
          snyk container test $REPOSITORY_URI:$IMAGE_TAG

  update-task-definition:
    runs-on: ubuntu-latest
    needs: Register-Image
    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Verificar presença do arquivo JSON
      - name: Validate JSON File
        run: |
          echo "Verifying ecs-task-definition-template.json..."
          ls -l ecs-task-definition-template.json || exit 1

      # 3. Substituir placeholders no JSON
      - name: Update Task Definition JSON
        run: |
          echo "Updating ECS Task Definition JSON..."
          sed -i "s|ECR_URI|${{ secrets.ECR_URI }}|g" ecs-task-definition-template.json
          sed -i "s|IMAGE_TAG|${{ needs.build-and-push.outputs.image_tag }}|g" ecs-task-definition-template.json
          sed -i "s|ECS_EXECUTION_ROLE_ARN|${{ secrets.ECS_EXECUTION_ROLE_ARN }}|g" ecs-task-definition-template.json
          sed -i "s|ECS_TASK_ROLE_ARN|${{ secrets.ECS_TASK_ROLE_ARN }}|g" ecs-task-definition-template.json

          # Adicionar variáveis de ambiente
          sed -i -e "/\"environment\"/a \ \ \ \ { \"name\": \"DB_NAME\", \"value\": \"${{ secrets.DB_NAME }}\" }," ecs-task-definition-template.json
          sed -i -e "/\"environment\"/a \ \ \ \ { \"name\": \"DB_HOST\", \"value\": \"${{ secrets.DB_HOST }}\" }," ecs-task-definition-template.json
          sed -i -e "/\"environment\"/a \ \ \ \ { \"name\": \"DB_USER\", \"value\": \"${{ secrets.DB_USER }}\" }," ecs-task-definition-template.json
          sed -i -e "/\"environment\"/a \ \ \ \ { \"name\": \"DB_PASSWORD\", \"value\": \"${{ secrets.DB_PASSWORD }}\" }," ecs-task-definition-template.json

          # Verificar JSON atualizado
          cat ecs-task-definition-template.json

      # 4. Registrar nova Task Definition no ECS
      - name: Register Task Definition
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Registering ECS Task Definition..."
          aws ecs register-task-definition --cli-input-json file://ecs-task-definition-template.json --debug

      # 5. Atualizar o serviço no ECS
      - name: Update ECS Service
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
          ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
        run: |
          echo "Updating ECS Service..."
          NEW_TASK_DEF_ARN=$(aws ecs describe-task-definition \
            --task-definition ${ECS_SERVICE} --query "taskDefinition.taskDefinitionArn" --output text)
          echo "New Task Definition ARN: $NEW_TASK_DEF_ARN"
          aws ecs update-service --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --task-definition $NEW_TASK_DEF_ARN --debug

  verify-deployment:
    runs-on: ubuntu-latest
    needs: update-task-definition
    steps:
      # 1. Verificar estado do serviço no ECS
      - name: Verify ECS Deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
          ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
        run: |
          echo "Verifying ECS Service Deployment..."
          aws ecs wait services-stable --cluster $ECS_CLUSTER --services $ECS_SERVICE
          echo "Deployment successful!"
