name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
   AWS_REGION: us-east-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get-commit.outputs.hash }}
    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Login no Amazon ECR
      - name: Log in to Amazon ECR
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}

      # 3. Obter hash curto do commit
      - name: Get short commit hash
        id: get-commit
        run: echo "hash=$(git rev-parse --short=5 HEAD)" >> $GITHUB_ENV

      # 4. Build e push da imagem Docker
      - name: Build and push Docker image
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          IMAGE_TAG: ${{ env.hash }}
          REPOSITORY_URI: ${{ secrets.ECR_URI }}
        run: |
          cd Docker
          docker build -t $REPOSITORY_URI:$IMAGE_TAG .
          docker push $REPOSITORY_URI:$IMAGE_TAG

          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "::set-output name=image_tag::${IMAGE_TAG}"

  update-task-definition:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      # 1. Gerar template do arquivo ecs-task-definition-template.json
      - name: Log in to AWS
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      # 2. Registrar nova Task Definition
      - name: Register Task Definition
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          aws ecs register-task-definition --cli-input-json file://ecs-task-definition-template.json

      # 3. Atualizar o serviço no ECS
      - name: Update ECS Service
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
          ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
        run: |
          # Obter o ARN da nova task definition
          NEW_TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition my-app-task --query "taskDefinition.taskDefinitionArn" --output text)
          echo "New Task Definition ARN: $NEW_TASK_DEF_ARN"
          
          # Atualizar o serviço com a nova task definition
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition $NEW_TASK_DEF_ARN

  verify-deployment:
    runs-on: ubuntu-latest
    needs: update-task-definition
    steps:
      # Verificar estado do serviço no ECS
      - name: Verify ECS Deployment
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
          ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
        run: |
          # Aguardar o serviço ser estável
          aws ecs wait services-stable --cluster $ECS_CLUSTER --services $ECS_SERVICE
          echo "Deployment successful!"